#!/usr/bin/env php
<?php
/**
 * Initialize the logger and AMQP connection.
 */
require __DIR__ . '/common.php';

$data = file_get_contents('/Users/james/Downloads/data.json');
$data = json_decode($data);

//
// foreach ($data as $index => $x) {
//     if ($index % 2) unset($data[$index]);
// }
// echo count($data) . PHP_EOL;

/**
 * Create an Overpass RPC server that exposes a single procedure named 'double'
 * which takes a single number as input and doubles it.
 */
$server = new Icecave\Overpass\Amqp\Rpc\AmqpRpcServer(
    $logger,
    $amqpChannel
);

$server->expose(
    'double',
    function ($value) use ($data) {
        return $data;
    }
);

pcntl_signal(
    SIGINT,
    function() use ($server) {
        $server->stop();
    }
);

/**
 * Service RPC requests forever!
 */
$server->run();
