#!/usr/bin/env php
<?php
/**
 * Initialize the logger and AMQP connection.
 */
require __DIR__ . '/common.php';

/**
 * Parse the command line parameters.
 *
 * sleep: Number of seconds to wait between making RPC requests.
 * timeout: The call timeout in seconds.
 */
list(, $sleep, $timeout) = $_SERVER['argv'] + [
    null,
    1, // sleep
    5, // timeout
];

/**
 * Create an Overpass RPC client.
 */
$client = new Icecave\Overpass\Amqp\Rpc\AmqpRpcClient(
    $amqpChannel,
    $timeout
);

$client->setLogger($logger);

/**
 * Make RPC calls forever!
 */
while (true) {
    $value = rand(0, 100000);
    $expected = $value * 2;

    try {
        $time = \microtime(true);
        $result = $client->double($value);
        echo (int)((\microtime(true) - $time) * 1000) . 'ms' . PHP_EOL;
        // assert($expected === $result);
        usleep($sleep * 1000000);

    } catch (Icecave\Overpass\Rpc\Exception\TimeoutException $e) {
        // ignore timeout exceptions (they will be logged anyway)
        echo "!!!";
    }
}

echo "WTF?";
